### ISSUE TITLE
Run face detection on grayscale image

### ISSUE THREAD

**Issue by msprog** [matlab-deep-learning/mtcnn-face-detection#14]
Can mtcnn implements gray images and how?

**Comment by justinpinkney** [comment]
If you have a grayscale image it is probably has only 1 colour channel. If you pad this to make it 3 channels it should be the compatible with the current detection (but I don't know what the effect on detection performance will be)

Something like:
```matlab
im = repmat(grayIm, [1, 1, 3]);
```

**Comment by justinpinkney** [comment]
For anyone interested in this the above line of code will be sufficient to make your greyscale image three channel, which can then be passed to the detector. But be aware that this will have a slight detrimental impact on the detection performance, see the image below (when running on the RGB version all the faces are detected).

![image](https://user-images.githubusercontent.com/605492/91227665-cba75e00-e71e-11ea-9d65-608972c0bdf2.png)
