### ISSUE TITLE
Support MATLAB versions earlier than R2019b

### ISSUE THREAD

**Issue by justinpinkney** [matlab-deep-learning/mtcnn-face-detection#2]
The current code uses MATLAB features introduced in release 2019b. However, with a bit of care it should be possible to port the existing code to earlier releases.

Please comment on or like this issue if you'd be interested in using the MTCNN face detector in releases earlier than R2019b.

**Comment by msprog** [comment]
Please I am interested in using the MTCNN face detector in releases earlier than R2019b.
I use  R2019a

**Comment by cuixing158** [comment]
我觉得以后更关注两点：
1、版本不重要，重要的是如何方便自由的设计损失函数，自动求导(R2019b)，各种细粒度操作灵活性要加大；
2、支持与其他框架的交互使用，比如使用onnx格式，但是目前onnx在matlab中使用效果非常差，很久得不到解决！

I think that I will pay more attention to two points in the future:
1、 The version is not important. What is important is how to conveniently and freely design the loss function and automatic differentiation(R2019b), and increase the flexibility of various fine-grained operations. 
2、Supports interactive use with other frameworks, such as using the onnx format, but the current use of [onnx](https://ww2.mathworks.cn/matlabcentral/fileexchange/67296-deep-learning-toolbox-converter-for-onnx-model-format) in matlab is very poor, and it has not been solved for a long time!

**Comment by justinpinkney** [comment]
Support for R2019a has been added, supporting any earlier releases gets tricky due to a lack of required layers in deep learning toolbox for earlier releases.
